package leetcode;

/**
 * 389. Find the Difference
 * Easy
 * -------------------------
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *
 * Example 1:
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 *
 * Example 2:
 * Input: s = "", t = "y"
 * Output: "y"
 *
 * Example 3:
 * Input: s = "a", t = "aa"
 * Output: "a"
 *
 * Example 4:
 * Input: s = "ae", t = "aea"
 * Output: "a"
 *
 * Constraints:
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lower-case English letters.
 */
public class Find_the_Difference_389 {
    public static char findTheDifference(String s, String t) {
        return findTheDifference_2(s, t);
    }

    /**
     * bit manipulation
     *
     * 验证通过：
     * Runtime: 1 ms, faster than 98.79% of Java online submissions for Find the Difference.
     * Memory Usage: 37.2 MB, less than 94.69% of Java online submissions for Find the Difference.
     *
     * @param s
     * @param t
     * @return
     */
    public static char findTheDifference_2(String s, String t) {
        char ret = 0;
        for (int i = 0; i < s.length(); i++) {
            ret ^= s.charAt(i);
            ret ^= t.charAt(i);
        }
        ret ^= t.charAt(t.length() - 1);
        return ret;
    }

    /**
     * 验证通过：
     * Runtime: 1 ms, faster than 98.79% of Java online submissions for Find the Difference.
     * Memory Usage: 37.1 MB, less than 97.28% of Java online submissions for Find the Difference.
     *
     * @param s
     * @param t
     * @return
     */
    public static char findTheDifference_1(String s, String t) {
        int[] count = new int[26];
        for (int i = 0; i < s.length(); i++) {
            char sc = s.charAt(i);
            char tc = t.charAt(i);
            count[sc - 'a']++;
            count[tc - 'a']--;
        }
        count[t.charAt(t.length() - 1) - 'a']--;
        for (int i = 0; i < 26; i++) {
            if (count[i] < 0) return (char) (i + 'a');
        }

        return ' ';
    }

    public static void main(String[] args) {
        do_func("abcd", "abcde", 'e');
        do_func("", "y", 'y');
        do_func("a", "aa", 'a');
        do_func("ae", "aea", 'a');
    }

    private static void do_func(String s, String t, char expected) {
        char ret = findTheDifference(s, t);
        System.out.println(ret);
        System.out.println(ret == expected);
        System.out.println("--------------");
    }
}
